// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcv46rqa0xqYXApNCGxZO5SKds80236n0',
    appId: '1:580234066545:web:72f70f1e5a225b0f4c39d0',
    messagingSenderId: '580234066545',
    projectId: 'scoreease-98ed8',
    authDomain: 'scoreease-98ed8.firebaseapp.com',
    storageBucket: 'scoreease-98ed8.firebasestorage.app',
    measurementId: 'G-PRLTHJ48ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Q9BhGbyacBczlmq3Ww6oJwnYI72C-Eg',
    appId: '1:580234066545:android:8c38180831901bbc4c39d0',
    messagingSenderId: '580234066545',
    projectId: 'scoreease-98ed8',
    storageBucket: 'scoreease-98ed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLhu887kjAUdVN_08-ExH-OI_JesmSAL4',
    appId: '1:580234066545:ios:b8722bfa793c67144c39d0',
    messagingSenderId: '580234066545',
    projectId: 'scoreease-98ed8',
    storageBucket: 'scoreease-98ed8.firebasestorage.app',
    iosBundleId: 'in.armid.scoreease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLhu887kjAUdVN_08-ExH-OI_JesmSAL4',
    appId: '1:580234066545:ios:b8722bfa793c67144c39d0',
    messagingSenderId: '580234066545',
    projectId: 'scoreease-98ed8',
    storageBucket: 'scoreease-98ed8.firebasestorage.app',
    iosBundleId: 'in.armid.scoreease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcv46rqa0xqYXApNCGxZO5SKds80236n0',
    appId: '1:580234066545:web:83d00271b28c83864c39d0',
    messagingSenderId: '580234066545',
    projectId: 'scoreease-98ed8',
    authDomain: 'scoreease-98ed8.firebaseapp.com',
    storageBucket: 'scoreease-98ed8.firebasestorage.app',
    measurementId: 'G-E7Y35XB986',
  );

}